name: Lint

on:
  workflow_dispatch:
  workflow_call:
  merge_group:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: yoriiis/actions/.github/workflows/lint.yml@main
    with:
      typescript-status: false
